### PR TITLE
Avoid testing floats for equality in PhotoViewController

### LINKED ISSUE #133: Potential wrong scale due to comparison of float value
The comparison [here](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/Pod%2FClasses%2Fios%2FNYTPhotoViewController.m#L161) is potentially wrong:

```objectivec
if (self.scalingImageView.zoomScale >= self.scalingImageView.maximumZoomScale) {
    newZoomScale = self.scalingImageView.minimumZoomScale;
}
```

In fact, I've just encountered this problem. I've changed this into:

```objectivec
if (self.scalingImageView.zoomScale >= self.scalingImageView.maximumZoomScale || 
ABS(self.scalingImageView.zoomScale - self.scalingImageView.maximumZoomScale) <= FLT_EPSILON) {
    newZoomScale = self.scalingImageView.minimumZoomScale;
}
```

### PR DESCRIPTION
**Pull request by cdzombak**
closes #133

### CODE REVIEW

**Comment by cdzombak** [comment]
@skyline75489, can you verify whether this approach fixes the issue you reported in #133? If so, I'd prefer this to the two-step comparison you outlined in that issue; this approach seems easier to read.

File: Pod/Classes/ios/NYTPhotoViewController.m [hunk 1]
```diff
@@ -157,8 +157,8 @@ - (void)didDoubleTapWithGestureRecognizer:(UITapGestureRecognizer *)recognizer {
     CGPoint pointInView = [recognizer locationInView:self.scalingImageView.imageView];
     
     CGFloat newZoomScale = self.scalingImageView.maximumZoomScale;
-    
-    if (self.scalingImageView.zoomScale >= self.scalingImageView.maximumZoomScale) {
+
+    if ((self.scalingImageView.zoomScale - self.scalingImageView.maximumZoomScale) >= 0.0) {
```
Comment (soundsokay) [inline Pod/Classes/ios/NYTPhotoViewController.m]: The change looks fine. However commenting out the if clause entirely causes no unit test failures. Expand the test coverage to include this?

Comment (steve-matthews) [inline Pod/Classes/ios/NYTPhotoViewController.m]: That's a good point, but I don't think we have any test coverage for the `UIKit` stuff in general so that becomes a much bigger task

Comment (skyline75489) [inline Pod/Classes/ios/NYTPhotoViewController.m]: @cdzombak  I don't think this works. I've been in a situation where `self.scalingImageView.zoomScale` is slightly smaller than `self.scalingImageView.maximumZoomScale`(well, not really small but strict-float-comparison small). That's why I add the `ABS` to deal with it.

Comment (cdzombak) [inline Pod/Classes/ios/NYTPhotoViewController.m]: @skyline75489 ah, that makes sense. thanks!

**Comment by soundsokay** [comment]
:+1:
