### PR TITLE
Fixes warnings and compilation errors on swift target

### LINKED ISSUE #103: Swift Sample Project Does Not Compile
As mentioned in #102.

### Steps to Reproduce

1. Clone the project.
2. Attempt to run the Swift sample application target.

### Expected Results

The app runs.

### Actual Results

The app fails to build with a number of errors.

### Platform and OS

Xcode Version 7.2 (7C68)

### PR DESCRIPTION
**Pull request by steve-matthews**
closes #103

### CODE REVIEW

File: Example/NYTPhotoViewer-Swift/PhotosProvider.swift [hunk 1]
```diff
@@ -29,7 +29,15 @@ class PhotosProvider: NSObject {
...
-            let photo = shouldSetImageOnIndex(photoIndex) ? ExamplePhoto(image: image, attributedCaptionTitle: title) : ExamplePhoto(attributedCaptionTitle: title)
+            
+            let imageData: NSData? = {
+                if let image = image {
+                    return UIImagePNGRepresentation(image)
+                }
+                return nil
+            }()
+            
+            let photo = shouldSetImageOnIndex(photoIndex) ? ExamplePhoto(imageData: imageData, attributedCaptionTitle: title) : ExamplePhoto(attributedCaptionTitle: title)
```
Comment (bcapps) [inline Example/NYTPhotoViewer-Swift/PhotosProvider.swift]: Since we're not using the animated image functionality, would it make more sense and be more instructive int he example project to instead initialize an `ExamplePhoto` with a `UIImage` directly instead of `NSData`? It seems like the more common use case, and this example may be a bit confusing for newcomers as to why they would have to call `UIImagePNGRepresentation` to get the image data in their model object.

**Comment by soundsokay** [comment]
:+1:
